### ISSUE TITLE
Downloads HTML instead of m4v for video podcast

### ISSUE THREAD

**Issue by jasttw** [dreamflasher/backup-podcasts#2]
Hello,

Thanks a lot for the great work!

I have started using and it succeeds almost always. But one thing I couldn't get around is that one podcast has video episodes but backup-podcasts downloads an html. The html downloaded is great though.

`<outline text="60-Second Adventures in Thought" type="rss" xmlUrl="http://podcast.open.ac.uk/feeds/thoughtexperiments-01/rss2.xml" htmlUrl="http://www3.open.ac.uk/study/undergraduate/arts-and-humanities/index.htm?LKCAMPAIGN=it001_sub&amp;MEDIA=it001_ahu" imageUrl="http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/60secs_jpeg_01691_std.jpg" />`

Is it something with the podcast itself or something that can be solved?

**Comment by dreamflasher** [comment]
Oh interesting, I haven't subscribed to any video podcasts, but I'd love to support it. I'll have a look at the podcast.

**Comment by dreamflasher** [comment]
So one item of that podcast looks like this:

```
<item>
    <title>Achilles and the Tortoise</title>
    <description>Ancient mathematical trickery  proves that a mighty hero cannot overtake a tortoise.</description>
    <link>http://www3.open.ac.uk/study/undergraduate/arts-and-humanities/index.htm?LKCAMPAIGN=it001_sub&amp;MEDIA=it001_ahu</link>
    <guid>http://podcast.open.ac.uk/feeds/thoughtexperiments-01/60second01.m4v</guid>
    <pubDate>Wed, 28 Sep 2011 15:43:04 +0100</pubDate>
    <enclosure url="http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/60second01.m4v" length="8627446" type="video/x-m4v" />
    <itunes:summary>Ancient mathematical trickery  proves that a mighty hero cannot overtake a tortoise.</itunes:summary>
    <itunes:keywords>Zeno, infinity,</itunes:keywords>
    <itunes:author>The Open University</itunes:author>
    <itunes:explicit>No</itunes:explicit>
    <itunes:subtitle>Ancient mathematical trickery  proves that a mighty hero cannot overtake a tortoise.</itunes:subtitle>
    <itunes:duration>00:01:07</itunes:duration>
    <itunesu:category itunesu:code="114" />
    <media:title>Achilles and the Tortoise</media:title>
    <media:description>Ancient mathematical trickery  proves that a mighty hero cannot overtake a tortoise.</media:description>
    <media:keywords>Zeno, infinity,</media:keywords>
    <media:thumbnail url="http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/60secs_jpeg_01691_std.jpg" />
    <media:group>
      <media:content medium="video" isDefault="true" url="http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/60second01.m4v" fileSize="8627446" type="video/x-m4v" duration="67.781666666667">
        <oupod:iframe>&lt;iframe src=&quot;http://player.open.ac.uk/embed/0a399e2b9b&quot; height=&quot;270&quot; width=&quot;480&quot; frameborder=&quot;0&quot; allowfullscreen &gt;&lt;/iframe&gt;</oupod:iframe>
        <oupod:iframe-oump>&lt;iframe src=&quot;http://mediaplayer.open.ac.uk/embed/pod/thoughtexperiments-01/0a399e2b9b&quot; height=&quot;270&quot; width=&quot;480&quot; frameborder=&quot;0&quot; allowfullscreen mozallowfullscreen webkitallowfullscreen &gt;&lt;/iframe&gt;</oupod:iframe-oump>
      </media:content>
      <media:content medium="document" url="http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/transcript/60second01_01691_16693.pdf" type="application/pdf" fileSize="16240">
        <media:category scheme="http://purl.org/steeple/mediacontent/rel">Transcript</media:category>
      </media:content>
    </media:group>
    <atom:link rel="alternate" type="application/pdf" title="Transcript for Achilles and the Tortoise" href="http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/transcript/60second01_01691_16693.pdf" length="16240" />
    <atom:link rel="alternate" type="text/html" title="Transcript for Achilles and the Tortoise" href="http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/transcript/60second01.html" length="1503" />
    <jwplayer:provider>http</jwplayer:provider>
    <jwplayer:http.startparam>start</jwplayer:http.startparam>
    <jwplayer:file>http://media-podcast.open.ac.uk/feeds/thoughtexperiments-01/60second01.m4v</jwplayer:file>
    <jwplayer:sharing.link>http://media-podcast.open.ac.uk/pod/thoughtexperiments-01/#!0a399e2b9b</jwplayer:sharing.link>
    <oupod:published>podcast</oupod:published>
    <oupod:published>itunes</oupod:published>
  </item>
```

So the podcast is "wrong", in the link they have the html page and that is being downloaded. Does this podcast work in podcast apps? 

Shall I add support to download `<media:group>` items?

**Comment by jasttw** [comment]
Thanks a lot for your response.

I wasn't able to understand the formatting of this rss since it had more than the common ones (transcript pdf, transcript html ...).

I have tried with Podcast Addict, Pocket casts and Castbox and they all download the m4v files.

I don't think this feature is in demand, but I personally feel that it's great to have a complete podcast archiver :⁠-⁠) but this can be a lower priority though.

**Comment by dreamflasher** [comment]
If those all support it, I wonder how they do it. The rss at hand clearly misuses the GUID attribute, so we can't download that.
There is also `enclosure url`… But I am pretty certain the default is the link attribute, at least it's the attribute which works for all podcasts I subscribed. 

I think it would definitely be cool to download the media:group:
https://www.rssboard.org/media-rss#media-group

I am thinking about how to name the files, because it probably makes sense to have the additional files next to the episodes, so maybe episodename + originalname?

**Comment by dreamflasher** [comment]
Okay, there is not really an official podcast specification, just guidelines by apple and google, so we have de-facto specifications:
https://podcasters.apple.com/support/823-podcast-requirements
https://support.google.com/podcast-publishers/answer/9889544?hl=en

And both of them require the enclosure tag. So I guess that's the correct link to backup.

**Comment by jasttw** [comment]
Yes, I think appending the original filename may in some cases add clarity as to what the file is (assuming others may call it transcript.pdf or credits.pdf or anything)

It's also better to handle episodes that have the same title. I think it currently overwrites the same file.

**Comment by dreamflasher** [comment]
Currently it shouldn't overwrite the same file, as I prepend the pubdate. So only if they have the same pubdate and same filename it would skip the second file. 

I have a good hunch how to save all interesting files – @jasttw what do you think, shall we save the transcripts (and potentially additional files) to the meta folder or next to the audios/videos?
I am inclined to put them in the meta folder and just keep the enclosure/main files in the main directory.

**Comment by jasttw** [comment]
> 

Yes I believe it's better to be in the meta folder since they are not the main podcast files. I have a couple of podcasts that don't download probably due to the differences in the xml formatting. I'll check those as well and see if there is a common way to handle as many formattings as possible.

**Comment by dreamflasher** [comment]
I just pushed a change that would download alternative files. It's downloading in the main folder now, give it a shot. If it works and also works for the other feeds you have, we can change the download folder.

Also I fixed it to download the `enclosure` url as the main file.

**Comment by jasttw** [comment]
Hello,

Thanks a lot for the effort! It downloaded the videos along with the transcripts perfectly

**Comment by dreamflasher** [comment]
Happy to hear! And it downloaded it in the main folder, right?

I am in contact with the author of parfive, the download manager I use, and I am working on a PR there to support temporary files, as soon as this is done, I'll change this project here to download transcripts to the meta data folder.

**Comment by jasttw** [comment]
Yes, it downloaded to the main folder. I'll keep on experimenting and report issues if I faced any :⁠-⁠)
